# site properties and page defaults
title: International Congress of Armenian Mycologists # title of site, used in tab name and elsewhere
email: icarmenian.mycologists@gmail.com # default email
google: Tania Kurbessoian # default name to search on Google Scholar
github: ICArmenian-Mycologists # default GitHub user/org, without the @
twitter: IC_ArmenianMyco # default Twitter handle, without the @
instagram: ICArmenian-Mycologists # default Instagram handle, without the @
youtube: ICArmenian-Mycologists # default YouTube channel handle
# site social media and other links
links:
  email: contact@your-lab.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: your-lab
  twitter: YourLabHandle
  youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: International Congress for Armenian Mycologists are American Armenian mycologists who are interested in collab$
      background: icons/ICAM-icon.jpg # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-github-metadata
  - jekyll-avatar
  - jekyll-gist
  - jekyll-mentions
  - jekyll-relative-links
  - jemoji

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
